Create plan backend
h3nk42/WebentwicklungHTW pull request #5
Opened 2021-01-11 20:08 UTC by h3nk42

(BE)

Feature: Create a plan and update the User Document to this plan_id

2021-01-12 09:22 UTC, viktorianer requested changes
Schaue mal unbedingt meine Folien zu den Thema REST und `actions` in Rails an und vielleicht noch mal dieses Tutorial.

Die `actions`, wie diese in REST üblich sind, sind hier beschrieben https://blog.usejournal.com/rails-and-the-seven-restful-routes-838e3e5e85d9

2021-01-12 09:22 UTC, viktorianer commented on backend/controllers/auth.js
> +
Leerzeilen können weg.

2021-01-12 09:22 UTC, viktorianer commented on backend/controllers/plans.js
> +exports.findPlanToOwner = async (req, res) => {
Ich würde es `findByOwner` nennen. Oder noch besser  `show`, wie es in REST üblich ist. https://blog.usejournal.com/rails-and-the-seven-restful-routes-838e3e5e85d9

2021-01-12 09:22 UTC, viktorianer commented on backend/controllers/plans.js
> +exports.findAllPlans = (req, res) => {
Ich würde es `findAll` nennen, da du hier bereits bei `plans` bist. Oder noch besser  `index`, wie es in REST üblich ist. https://blog.usejournal.com/rails-and-the-seven-restful-routes-838e3e5e85d9

2021-01-12 09:22 UTC, viktorianer commented on backend/controllers/plans.js
> +exports.createPlan = async (req, res) => {
Ich würde es `create` nennen, da du hier bereits bei `plans` bist.

2021-01-12 09:22 UTC, viktorianer commented on backend/controllers/plans.js
> +
Leerzeilen

2021-01-12 09:22 UTC, viktorianer commented on backend/controllers/users.js
> +
Kann auch weg.

2021-01-12 09:22 UTC, viktorianer commented on backend/models/User.js
> +
Kann weg, nicht nötig hier eine Leerzeile zu schreiben.

2021-01-12 20:05 UTC, h3nk42 commented
Danke für den Link, das mit dem Rest ist mir noch etwas schwer gefallen!

2021-01-13 11:05 UTC, viktorianer approved these changes
👍🏼

2021-01-13 11:07 UTC, viktorianer commented
Für dich als Überblick:
Ich denke, dass du min. 2 solche Features wie diese noch einbauen musst (BE), damit du genug Features hast. 💯

2021-01-13 11:09 UTC, h3nk42 commented
> Für dich als Überblick:
> Ich denke, dass du min. 2 solche Features wie diese noch einbauen musst (BE), damit du genug Features hast.

Alles Klar, theres more to come :) vielen Dank Viktor :+1:

2021-01-13 11:10 UTC, merged